environment:
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10
    - nodejs_version: 0.11

install:
  - SET PATH=c:\python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm test
