environment:
  matrix:
    - nodejs_version: 0.11
    - nodejs_version: 0.10
    - nodejs_version: 0.8

install:
  - node --version
  - npm --version
  - npm install -g node-gyp
  - SET PATH=c:\python27;%PATH%
  - SET PATH=%APPDATA%\npm;%PATH%
  - git submodule update --init
  - npm install --build-from-source --msvs_version=2012

test_script:
  - cmd: npm test
